"""Initial check

Revision ID: a6054da936d9
Revises: 
Create Date: 2026-05-11 11:11:30.555188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6054da936d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # =========================
    # USER
    # =========================
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='wp'
    )
    op.create_index(op.f('ix_wp_user_email'), 'user', ['email'], unique=True, schema='wp')
    
    # =========================
    # REFRESH TOKEN
    # =========================
    op.create_table('refreshtoken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['wp.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='wp'
    )
    op.create_index(op.f('ix_wp_refreshtoken_token_hash'), 'refreshtoken', ['token_hash'], unique=False, schema='wp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wp_refreshtoken_token_hash'), table_name='refreshtoken', schema='wp')
    op.drop_table('refreshtoken', schema='wp')
    op.drop_index(op.f('ix_wp_user_email'), table_name='user', schema='wp')
    op.drop_table('user', schema='wp')
    # ### end Alembic commands ###
