"""Add finance module

Revision ID: ae9dc220f9ce
Revises: 72e7797d2539
Create Date: 2026-05-28 11:01:10.289540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9dc220f9ce'
down_revision: Union[str, Sequence[str], None] = '72e7797d2539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # =========================
    # ESPENSE
    # =========================
    op.create_table('expense',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('FOOD', 'ALCOHOL', 'SERVICE', 'ATTIRE', 'ACCOMMODATION', 'OTHER', name='expensecategory'), nullable=False),
    sa.Column('is_included_in_wedding_total', sa.Boolean(), nullable=False),
    sa.Column('calculation_strategy', sa.Enum('FIXED', 'PER_ADULT', 'PER_CHILD', 'PER_GUEST', 'PER_INVITATION', 'CUSTOM_MULTIPLIER', name='calculationstrategy'), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('custom_multiplier', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['wp.event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='wp'
    )
    op.create_index('ix_expense_event_id', 'expense', ['event_id'], unique=False, schema='wp')
    
    # =========================
    # PAYMENT
    # =========================
    op.create_table('payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expense_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_by', sa.String(length=255), nullable=True),
    sa.Column('payment_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['wp.expense.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='wp'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment', schema='wp')
    op.drop_index('ix_expense_event_id', table_name='expense', schema='wp')
    op.drop_table('expense', schema='wp')
    # ### end Alembic commands ###
